### ISSUE TITLE
bids-mriqc is not usable - likely due to our env setting 

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/containers#118]
```
 ~/my-experiments/ds000003-qc  master ▓▒░──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────░▒▓ 2m 18s  04:28:26 ❯ datalad containers-run -n bids-mriqc -- --help
[WARNING] Requested extension 'next' is not available 
[INFO   ] Making sure inputs are available (this may take some time) 
[INFO   ] == Command start (output follows) ===== 
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/opt/conda/bin/python3.11'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = '/opt/conda/lib/python3.11'
  sys._base_executable = '/opt/conda/bin/python3.11'
  sys.base_prefix = '/opt/conda'
  sys.base_exec_prefix = '/opt/conda'
  sys.platlibdir = 'lib'
  sys.executable = '/opt/conda/bin/python3.11'
  sys.prefix = '/opt/conda'
  sys.exec_prefix = '/opt/conda'
  sys.path = [
    '/opt/conda/lib/python311.zip',
    '/opt/conda/lib/python3.11',
    '/opt/conda/lib/python3.11/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
PermissionError: [Errno 13] Permission denied: '/opt/conda/lib/python3.11/encodings/__init__.py'
[INFO   ] == Command exit (modification check follows) ===== 
run(error): /home/yoh/my-experiments/ds000003-qc (dataset) [./containers/scripts/singularity_cmd run...]
action summary:
  get (notneeded: 2)
  run (error: 1)
```

<details>
<summary>edit: only two most recent versions</summary> 

```shell
$> for v in ./images/bids/bids-mriqc--*; do echo -n "$v "; chronic singularity run $v --version /tmp /tmp group && echo ok; done
./images/bids/bids-mriqc--0.15.0.sing ok
./images/bids/bids-mriqc--0.15.1.sing ok
./images/bids/bids-mriqc--0.15.2.sing ok
./images/bids/bids-mriqc--0.16.0.sing ok
./images/bids/bids-mriqc--0.16.1.sing ok
./images/bids/bids-mriqc--22.0.1.sing ok
./images/bids/bids-mriqc--22.0.2.sing ok
./images/bids/bids-mriqc--22.0.3.sing ok
./images/bids/bids-mriqc--22.0.4.sing ok
./images/bids/bids-mriqc--22.0.5.sing ok
./images/bids/bids-mriqc--22.0.6.sing ok
./images/bids/bids-mriqc--23.0.0.sing ok
./images/bids/bids-mriqc--23.0.1.sing ok
./images/bids/bids-mriqc--23.1.0.sing ok
./images/bids/bids-mriqc--23.1.1.sing Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/opt/conda/bin/python3.11'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = '/opt/conda/lib/python3.11'
  sys._base_executable = '/opt/conda/bin/python3.11'
  sys.base_prefix = '/opt/conda'
  sys.base_exec_prefix = '/opt/conda'
  sys.platlibdir = 'lib'
  sys.executable = '/opt/conda/bin/python3.11'
  sys.prefix = '/opt/conda'
  sys.exec_prefix = '/opt/conda'
  sys.path = [
    '/opt/conda/lib/python311.zip',
    '/opt/conda/lib/python3.11',
    '/opt/conda/lib/python3.11/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
PermissionError: [Errno 13] Permission denied: '/opt/conda/lib/python3.11/encodings/__init__.py'
./images/bids/bids-mriqc--24.0.0.sing Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/opt/conda/bin/python3.11'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = '/opt/conda/lib/python3.11'
  sys._base_executable = '/opt/conda/bin/python3.11'
  sys.base_prefix = '/opt/conda'
  sys.base_exec_prefix = '/opt/conda'
  sys.platlibdir = 'lib'
  sys.executable = '/opt/conda/bin/python3.11'
  sys.prefix = '/opt/conda'
  sys.exec_prefix = '/opt/conda'
  sys.path = [
    '/opt/conda/lib/python311.zip',
    '/opt/conda/lib/python3.11',
    '/opt/conda/lib/python3.11/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
PermissionError: [Errno 13] Permission denied: '/opt/conda/lib/python3.11/encodings/__init__.py'

```
</details>

**Comment by yarikoptic** [comment]
that particular one fixed up in 78bfcd83d54e32fe263c577d7ec5bdf1c34e94fa by rebuilding images with Singularity file doing extra chmod'ing.  Hopefully upstream fixes before next release.

**Comment by bpinsard** [comment]
same fix needs to be applied to 24.0.2

**Comment by yarikoptic** [comment]
grr, fixing it... if only we figured  underlying issue

**Comment by bpinsard** [comment]
thanks!
