### ISSUE TITLE
MRIQC OOM error causes unhelpful nipype NodeExecutionError 

### ISSUE THREAD

**Issue by asmacdo** [ReproNim/containers#82]
### Summary

I am running MRIQC container on sample data, which fails with the error:

```
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node synthstrip.

RuntimeError: subprocess exited with code 137.
```
This error appears to be caused by OOM

### Actual behavior

Using a vm with only 2GB of RAM, which was apparently not enough.  I am using the ds000003-demo sample data.

Failing command:
```
$ datalad containers-run --explicit --container-name containers/bids-mriqc --input sourcedata --output out '{inputs}' '{outputs}' participant group -w workdir
```

However, the NodeExecutionError did not provide enough details to debug.

```
230207-12:49:42,425 nipype.workflow ERROR:
	 Node synthstrip.a1 failed to run on host ubuntu2204.localdomain.
230207-12:49:42,432 nipype.workflow ERROR:
	 Saving crash info to /home/vagrant/DEMO/ds000003-qc/out/logs/crash-20230207-124942-mriqc-synthstrip.a1-984383a2-7814-40ad-829e-c3890e130d91.txt
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 60, in run_node
    result["result"] = node.run(updatehash=updahidden with tehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipypeAdditional questions/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node synthstrip.

RuntimeError: subprocess exited with code 137.

Traceback (most recent call last):
  File "/opt/conda/bin/mriqc", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/mriqc/cli/run.py", line 159, in main
    mriqc_wf.run(**_plugin)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 184, in run
    self._clean_queue(jobid, graph, result=result)
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 256, in _clean_queue
    raise RuntimeError("".join(result["traceback"]))
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 60, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node synthstrip.

RuntimeError: subprocess exited with code 137.

230207-12:49:59,848 nipype.workflow WARNING:
	 [Node] Error on "mriqc_wf.anatMRIQC.synthstrip_wf.synthstrip" (/home/vagrant/DEMO/ds000003-qc/workdir/mriqc_wf/anatMRIQC/synthstrip_wf/_in_file_..home..vagrant..DEMO..ds000003-qc..sourcedata..sub-02..anat..sub-02_T1w.nii.gz/synthstrip)
```

I looked at the file with the saved output, and it did not provide additional info.

```
$ cat /home/vagrant/DEMO/ds000003-qc/out/logs/crash-20230207-124942-mriqc-synthstrip.a1-984383a2-7814-40ad-829e-c3890e130d91.txt
Node: mriqc_wf.anatMRIQC.synthstrip_wf.synthstrip
Working directory: /home/vagrant/DEMO/ds000003-qc/workdir/mriqc_wf/anatMRIQC/synthstrip_wf/_in_file_..home..vagrant..DEMO..ds000003-qc..sourcedata..sub-13..anat..sub-13_T1w.nii.gz/synthstrip

Node inputs:

args = <undefined>
border_mm = 1
environ = {}
in_file = /home/vagrant/DEMO/ds000003-qc/workdir/mriqc_wf/anatMRIQC/synthstrip_wf/_in_file_..home..vagrant..DEMO..ds000003-qc..sourcedata..sub-13..anat..sub-13_T1w.nii.gz/pre_n4/clipped_corrected.nii.gz
model = /opt/freesurfer/models/synthstrip.1.pt
out_file = <undefined>
out_mask = <undefined>
use_gpu = False

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 60, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node synthstrip.
```

### Expected behavior
,  ask because I got a talk accepted (applied while still at Red Hat)
If possible it would be nice if there was something in the output about OOM error.
 [others have experienced this as well](https://groups.google.com/g/mriqc-users/c/MqJsKlNCgzo)

### How to replicate the behavior

Run on a vm without enough memory.

**I increased memory, and it all worked as expected.**

### Platform details:

Ubuntu 22.04 vagrant box

### Additional questions

**I increased memory, and it all worked as expected.**

1. it is not obvious which part of the stack is failing, is this an upstream issue with mriqc/nipype/fmriprep/synthstrip?
2. I'm going to limit the README example workflow to a single participant and recommend 8GB

**Comment by yarikoptic** [comment]
that boils down to those aspects on "how much resources should be needed for a given container/workflow". there is nothing for us really to "fix" ATM but we indeed should come up with a way to annotate (some if not all) containers not only with metadata for discovery, but metadata on some typical use cases and resources demands.

**Comment by asmacdo** [comment]
I agree some annotations would be helpful, but I'm much more interested in providing the user with a more helpful error

**Comment by asmacdo** [comment]
137 /facepalm
