### ISSUE TITLE
apptainer, cache write error

### ISSUE THREAD

**Issue by bpinsard** [ReproNim/containers#97]
I had code that was running fMRIPrep from repronim containers on an HPC, but changing singularity to apptainer I now get the following error:

```
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 20, in build_workflow
    from ..workflows.base import init_fmriprep_wf
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 20, in <module>
    from ..interfaces import SubjectSummary, AboutSummary, DerivativesDataSink
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/interfaces/__init__.py", line 5, in <module>
    from niworkflows.interfaces import (
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/__init__.py", line 4, in <module>
    from .masks import BETRPT as BET
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/masks.py", line 21, in <module>
    from seaborn import color_palette
  File "/usr/local/miniconda/lib/python3.7/site-packages/seaborn/__init__.py", line 2, in <module>
    from .rcmod import *  # noqa: F401,F403
  File "/usr/local/miniconda/lib/python3.7/site-packages/seaborn/rcmod.py", line 7, in <module>
    from . import palettes
  File "/usr/local/miniconda/lib/python3.7/site-packages/seaborn/palettes.py", line 9, in <module>
    from .utils import desaturate, get_color_cycle
  File "/usr/local/miniconda/lib/python3.7/site-packages/seaborn/utils.py", line 14, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/pyplot.py", line 31, in <module>
    import matplotlib.colorbar
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/contour.py", line 25, in <module>
    import matplotlib.texmanager as texmanager
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/texmanager.py", line 83, in <module>
    class TexManager(object):
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/texmanager.py", line 91, in TexManager
    mkdirs(texcache)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 863, in mkdirs
    os.makedirs(newdir, mode=mode, exist_ok=True)
  File "/usr/local/miniconda/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [Errno 38] Function not implemented: '/home/fmriprep/.cache/matplotlib/tex.cache'
```

Are you aware of any difference introduced with apptainer that would make some filesystem non-writable.
Should I modify the singularity_cmd to bind a writable tmp folder to that cache path?

**Comment by yarikoptic** [comment]
> Are you aware of any difference introduced with apptainer that would make some filesystem non-writable.

Frankly I am not very verse in apptainer yet, so the answer would be "No" but not because there is no such differences ;)

But are you certain it is the permission (not-writeable) since it is not about Permission denied ?

> Should I modify the singularity_cmd to bind a writable tmp folder to that cache path?

Why not?  FWIW -- I give you my blessing ;)

**Comment by bpinsard** [comment]
Sorry for the long delay in reply.
I got to dig into that issue again, and it is not a permission error, just the fact that it's not possible to write in an apptainer container (contrary to docker) except in binds.
This cache folder is prepopulated in the container creation but is not writable then.
